### ISSUE TITLE
Add TGA block 

### ISSUE THREAD

**Issue by jdbocarsly** [the-grey-group/datalab#276]

**Comment by ml-evs** [comment]
Added an TGA example file to the branch [`ml-evs/example_TGA_dat`](https://github.com/the-grey-group/datalab/tree/ml-evs/example_TGA_dat) in e45d191

**Comment by ml-evs** [comment]
Ok I also added a parser + test to that branch (will make a PR).

Can decide how to structure it wrt. echem/NMR.
