### ISSUE TITLE
Speed up CI tests

### ISSUE THREAD

**Issue by jdbocarsly** [the-grey-group/datalab#44]
We have discussed some possible ways to streamline the CI tests so that they run faster/use less compute time. Current time was about 10 minutes to check #39.

-Do we really need to build the webapp both inside and outside of the docker container, or should we just do all of the building, linting, and testing inside the docker container. 
- Can we re-organize to make some of the longer steps happen in parallel.

**Comment by ml-evs** [comment]
Caching of the docker build is now working as of #497
