### ISSUE TITLE
docs: link to docs in README seems internal

### ISSUE THREAD

**Issue by simontaurus** [the-grey-group/datalab#447]
link to docs in README seems internal (at least it requires to login first)
https://github.com/the-grey-group/datalab/blob/7062af272b215a228ed7704757d80482aafd7160/README.md?plain=1#L61
I guess it should be `https://the-datalab.readthedocs.io`

**Comment by ml-evs** [comment]
Thanks @simontaurus, this should have been updated once our paid readthedocs account trial ended...
