### ISSUE TITLE
Chat block: need to migrate `openai` for `>=v1.0.0`

### ISSUE THREAD

**Issue by jdbocarsly** [the-grey-group/datalab#554]
The api we used in the chat block is no longer supported, so we should pin to v0.28 : 

![Screen Shot 2024-01-25 at 1 30 58 PM](https://github.com/the-grey-group/datalab/assets/32345545/0a55a517-74aa-45c6-92eb-44a8f202b7fc)

**Comment by ml-evs** [comment]
Here's the link to the migration guide from the screenshot: https://github.com/openai/openai-python/discussions/742

**Comment by ml-evs** [comment]
I think this is closed by #661 (@jdbocarsly @vrajpatel9988 can correct me if I am wrong)

**Comment by jdbocarsly** [comment]
should be!

**Comment by vrajpatel9988** [comment]
Yes!
