### ISSUE TITLE
Users can't edit starting materials and equipment

### ISSUE THREAD

**Issue by jdbocarsly** [the-grey-group/datalab#671]
Starting Materials and Equipment both are set up to not have any creator -- they can therefore be created or viewed by anyone logged into the server. However, they receive an error when attempting to edit and save those entries. 

Reported by @HHL98.

**Comment by ml-evs** [comment]
They also can't delete them...

**Comment by ml-evs** [comment]
I'm wondering if the best default policy for equipment/starting materials approach here is still to retain `creators` of starting materials but to allow anyone to view/edit (and then the creator or an admin can delete). 

(Need a good name for this kind of entry type -- shared? communal?)
