### ISSUE TITLE
Suggestion: Changing user images

### ISSUE THREAD

**Issue by MJCliffe** [the-grey-group/datalab#739]
The user pictures shown in the roundels don't appear to be editable which makes it hard to identify who is who. If it is possible already, perhaps add this to the Account Settings page to make it easy to find.

**Comment by ml-evs** [comment]
Avatars are currently handled by https://gravatar.com/, if users register their and add an avatar for the datalab "contact email" (settable in the account settings) then it should show up. We *could* host avatars ourselves but its probably quite low priority for us

**Comment by ml-evs** [comment]
Closed by #744 -- though we do need to verify email addresses still
