### ISSUE TITLE
Suggestion: Generic data block

### ISSUE THREAD

**Issue by MJCliffe** [the-grey-group/datalab#742]
Would be good to have a generic .xy/.csv type datablock to visualise simple datasets that don't yet have proper data blocks. An extension feature would be adding in axes labels, picking which columns to plot and the header/footer to ignore, but a simple generic block (analogous to media) would be good.

**Comment by ml-evs** [comment]
This is closed by #592; very close to merging and I can do another push on it before the next release.

**Comment by ml-evs** [comment]
Closed by #592
